# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160807_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='photos',
        ),
    ]
