# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_information_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='photos',
        ),
    ]
