# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160814_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=projects.models.generate_filename), null=True, size=None),
        ),
    ]
