# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160814_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='photos',
        ),
        migrations.AddField(
            model_name='images',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Information'),
        ),
    ]
